name: vpnclient
description: "VPN client for connectiong to IKEv2 VPN Server"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  # dart_code_linter:
  #   git:
  #     url: https://github.com/The-Redhat/dart-code-linter.git
  #     ref: fix_analyzer_6.0_errors
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_svg: ^2.0.10+1
  get_it: ^7.6.7
  ikev2_dart:
    path: ../ikev2_dart
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.3
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  uuid: ^4.3.3
  fluttertoast: ^8.2.4
  http: ^1.2.1
  
dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  lint: ^2.1.2



# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  assets:
     - assets/

  fonts:
    - family: Manrope
      fonts: 
        - asset: fonts/Manrope-Bold.ttf
          weight: 700
        - asset: fonts/Manrope-ExtraBold.ttf
          weight: 800
        - asset: fonts/Manrope-ExtraLight.ttf
          weight: 200
        - asset: fonts/Manrope-Light.ttf
          weight: 300
        - asset: fonts/Manrope-Medium.ttf
          weight: 500
        - asset: fonts/Manrope-Regular.ttf
          weight: 400
        - asset: fonts/Manrope-SemiBold.ttf
          weight: 600
  
